import Head from 'next/head'
import Image from 'next/image'
import maze from './assets/maze.jpg'
import styles from "./Home.module.css";
import App from "./_app";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Founderz</title>
        <meta name="description" content="Generated by create next app" />
        <Image src={maze} />
      </Head>

      <main className={styles.main}>
        <App />
      </main>
    </div>
  );
}
